name: Test

on:
  pull_request:
    branches:
      - 'staging'
      - 'main'
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write
  checks: write
  issues: write

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - name: Install dependencies (composer)
        run: composer install
      - name: Lint
        run: composer lint
      - name: Run tests
        run: composer test-ci
      - name: Report coverage
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./coverage.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'results.xml'
          github-token: ${{ secrets.GITHUB_TOKEN }}
